### ISSUE TITLE
Deleted Records Are Restored When Calling the open Method

### ISSUE THREAD

**Issue by gioxoay** [chronoDave/leaf-db#15]
When using the Leaf-DB package, deleted records unexpectedly reappear in the database after the open method is called. This issue occurs even when the records were successfully deleted during the current session. It seems that the deletion is not being persisted or properly handled, causing the data to be restored upon reopening the database.

Steps to Reproduce:

1. Open a Leaf-DB database.
2. Insert some records.
3. Delete one or more records.
4. Close curent sesion
5. Open database and call the open method again to reopen the database.
6. Observe that the previously deleted records have been restored.

**Expected Behavior:**
Deleted records should remain deleted and not be restored when the open method is called.

**Actual Behavior:**
Deleted records are restored and appear in the database after calling the open method.

**Impact:**
This issue may lead to data inconsistencies and unexpected behavior in applications relying on the persistence of deleted records.

**Comment by chronoDave** [comment]
Thanks for opening this issue. It's been fixed in `10.1.1`.
